// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbq4aAOXiNuoHzb229RQbnicNhjw7U_h4',
    appId: '1:111736009081:web:1da138fa2adcd26d7e7fa8',
    messagingSenderId: '111736009081',
    projectId: 'hearfit-8fc43',
    authDomain: 'hearfit-8fc43.firebaseapp.com',
    databaseURL: 'https://hearfit-8fc43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hearfit-8fc43.firebasestorage.app',
    measurementId: 'G-1SFEJ740LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlhTgccRR2Q9U8OWBdXfHrStXXYlawUE',
    appId: '1:111736009081:android:d66b3d6bb341e0bf7e7fa8',
    messagingSenderId: '111736009081',
    projectId: 'hearfit-8fc43',
    databaseURL: 'https://hearfit-8fc43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hearfit-8fc43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZfA2z-SvsxCwyuG5Hb1BeQuE56jQIyXU',
    appId: '1:111736009081:ios:7bae148c1590e7607e7fa8',
    messagingSenderId: '111736009081',
    projectId: 'hearfit-8fc43',
    databaseURL: 'https://hearfit-8fc43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hearfit-8fc43.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbq4aAOXiNuoHzb229RQbnicNhjw7U_h4',
    appId: '1:111736009081:web:fd0f39bad99fc2327e7fa8',
    messagingSenderId: '111736009081',
    projectId: 'hearfit-8fc43',
    authDomain: 'hearfit-8fc43.firebaseapp.com',
    databaseURL: 'https://hearfit-8fc43-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hearfit-8fc43.firebasestorage.app',
    measurementId: 'G-H3WS00E40B',
  );
}
